/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "AxiomV2Client",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AxiomV2Client__factory>;
    getContractFactory(
      name: "Badge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Badge__factory>;
    getContractFactory(
      name: "TicTacToe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TicTacToe__factory>;
    getContractFactory(
      name: "IAxiomV2Client",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAxiomV2Client__factory>;
    getContractFactory(
      name: "IAxiomV2HeaderVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAxiomV2HeaderVerifier__factory>;
    getContractFactory(
      name: "IAxiomV2Query",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAxiomV2Query__factory>;
    getContractFactory(
      name: "IAxiomV2Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAxiomV2Verifier__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "AxiomV2Client",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AxiomV2Client>;
    getContractAt(
      name: "Badge",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Badge>;
    getContractAt(
      name: "TicTacToe",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TicTacToe>;
    getContractAt(
      name: "IAxiomV2Client",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAxiomV2Client>;
    getContractAt(
      name: "IAxiomV2HeaderVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAxiomV2HeaderVerifier>;
    getContractAt(
      name: "IAxiomV2Query",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAxiomV2Query>;
    getContractAt(
      name: "IAxiomV2Verifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAxiomV2Verifier>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
