/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IAxiomV2HeaderVerifierInterface extends ethers.utils.Interface {
  functions: {
    "getSourceChainId()": FunctionFragment;
    "verifyQueryHeaders(bytes32,(uint32,bytes32[],bytes32[]))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getSourceChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyQueryHeaders",
    values: [
      BytesLike,
      {
        snapshotPmmrSize: BigNumberish;
        proofMmrPeaks: BytesLike[];
        mmrComplementOrPeaks: BytesLike[];
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSourceChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyQueryHeaders",
    data: BytesLike
  ): Result;

  events: {
    "UpdateAxiomCoreAddress(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "UpdateAxiomCoreAddress"): EventFragment;
}

export type UpdateAxiomCoreAddressEvent = TypedEvent<
  [string] & { axiomCoreAddress: string }
>;

export class IAxiomV2HeaderVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAxiomV2HeaderVerifierInterface;

  functions: {
    getSourceChainId(overrides?: CallOverrides): Promise<[BigNumber]>;

    verifyQueryHeaders(
      proofMmrKeccak: BytesLike,
      mmrWitness: {
        snapshotPmmrSize: BigNumberish;
        proofMmrPeaks: BytesLike[];
        mmrComplementOrPeaks: BytesLike[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getSourceChainId(overrides?: CallOverrides): Promise<BigNumber>;

  verifyQueryHeaders(
    proofMmrKeccak: BytesLike,
    mmrWitness: {
      snapshotPmmrSize: BigNumberish;
      proofMmrPeaks: BytesLike[];
      mmrComplementOrPeaks: BytesLike[];
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getSourceChainId(overrides?: CallOverrides): Promise<BigNumber>;

    verifyQueryHeaders(
      proofMmrKeccak: BytesLike,
      mmrWitness: {
        snapshotPmmrSize: BigNumberish;
        proofMmrPeaks: BytesLike[];
        mmrComplementOrPeaks: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "UpdateAxiomCoreAddress(address)"(
      axiomCoreAddress?: null
    ): TypedEventFilter<[string], { axiomCoreAddress: string }>;

    UpdateAxiomCoreAddress(
      axiomCoreAddress?: null
    ): TypedEventFilter<[string], { axiomCoreAddress: string }>;
  };

  estimateGas: {
    getSourceChainId(overrides?: CallOverrides): Promise<BigNumber>;

    verifyQueryHeaders(
      proofMmrKeccak: BytesLike,
      mmrWitness: {
        snapshotPmmrSize: BigNumberish;
        proofMmrPeaks: BytesLike[];
        mmrComplementOrPeaks: BytesLike[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSourceChainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verifyQueryHeaders(
      proofMmrKeccak: BytesLike,
      mmrWitness: {
        snapshotPmmrSize: BigNumberish;
        proofMmrPeaks: BytesLike[];
        mmrComplementOrPeaks: BytesLike[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
